import type { uploadValidationDocumentBodySchema, uploadValidationDocumentResponseSchema, resubmitValidationDocumentBodySchema, resubmitValidationDocumentResponseSchema, listPendingValidationDocumentsParamsSchema, listPendingValidationDocumentsQuerySchema, listPendingValidationDocumentsResponseSchema, reviewValidationDocumentParamsSchema, reviewValidationDocumentBodySchema, reviewValidationDocumentResponseSchema, uploadOwnerContractResponseSchema } from '@domains/users/actions/document/schemas'
import type { z } from 'zod'

export type UploadValidationDocumentBody = z.infer<typeof uploadValidationDocumentBodySchema>
export type UploadValidationDocumentResponse = z.infer<typeof uploadValidationDocumentResponseSchema>
export type ResubmitValidationDocumentBody = z.infer<typeof resubmitValidationDocumentBodySchema>
export type ResubmitValidationDocumentResponse = z.infer<typeof resubmitValidationDocumentResponseSchema>
export type ListPendingValidationDocumentsParams = z.infer<typeof listPendingValidationDocumentsParamsSchema>
export type ListPendingValidationDocumentsQuery = z.infer<typeof listPendingValidationDocumentsQuerySchema>
export type ListPendingValidationDocumentsResponse = z.infer<typeof listPendingValidationDocumentsResponseSchema>
export type ReviewValidationDocumentParams = z.infer<typeof reviewValidationDocumentParamsSchema>
export type ReviewValidationDocumentBody = z.infer<typeof reviewValidationDocumentBodySchema>
export type ReviewValidationDocumentResponse = z.infer<typeof reviewValidationDocumentResponseSchema>
export type UploadOwnerContractResponse = z.infer<typeof uploadOwnerContractResponseSchema>